# Generated by Django 4.0.4 on 2023-02-26 23:24

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=4),
        ),
    ]
